### ISSUE TITLE
Transistor 

### ISSUE THREAD

**Issue by vick2075** [laurent90git/DAE-Scipy#5]
Hi,

I tried to replicate the Transistor code as found here: https://archimede.uniba.it/~testset/problems/transamp.php
from the Fortran code: transamp.f in Python.

But the radauDAE does not work with following errors:
Warning (from warnings module):
  File "C:\Users\Vickram\Downloads\ODEv7\DAE\radauDAE.py", line 867
    dW_true_max_ite = rate ** (self.NEWTON_MAXITER - k) / (1 - rate) * dW_norm # estimated true error after max number of iterations
RuntimeWarning: overflow encountered in scalar power

Warning (from warnings module):
  File "C:\Users\Vickram\Downloads\ODEv7\DAE\radauDAE.py", line 348
    return lu_factor(A, overwrite_a=True)
LinAlgWarning: Diagonal number 8 is exactly zero. Singular matrix.

Warning (from warnings module):
  File "C:\Users\Vickram\Downloads\ODEv7\DAE\radauDAE.py", line 585
    LU_real    = self.lu( self.hscale @ (MU_REAL    / h * self.mass_matrix - J) )
RuntimeWarning: overflow encountered in scalar divide

Warning (from warnings module):
  File "C:\Users\Vickram\Downloads\ODEv7\DAE\radauDAE.py", line 585
    LU_real    = self.lu( self.hscale @ (MU_REAL    / h * self.mass_matrix - J) )
RuntimeWarning: invalid value encountered in multiply

Warning (from warnings module):
  File "C:\Users\Vickram\Downloads\ODEv7\DAE\radauDAE.py", line 585
    LU_real    = self.lu( self.hscale @ (MU_REAL    / h * self.mass_matrix - J) )
RuntimeWarning: invalid value encountered in matmul
Traceback (most recent call last):
  File "C:\Users\Vickram\Downloads\ODEv7\DAE\transamp.py", line 97, in <module>
    assert_(sol.success, msg='DAE solution failed with solver {method}')
  File "C:\Users\Vickram\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\testing\_private\utils.py", line 88, in assert_
    raise AssertionError(smsg)
AssertionError: DAE solution failed with solver {method}

Can you please help me out?

Thanks
Vickram

[transamp.py.txt](https://github.com/laurent90git/DAE-Scipy/files/14776419/transamp.py.txt)

**Comment by vick2075** [comment]
The script worked as I had the following in problem equations:
(U4/-Ub)/R4+alpha * fac1 instead of 
(U4-Ub)/R4+alpha*fac1
